{"uid":"7050924f65451d3","name":"Get Goals","fullName":"cypress/e2e/api-tests/goals.cy.ts#Check goals functionality on clickup Get Goals","historyId":"1c500b9abc6dd76bf3609991642590f9:d41d8cd98f00b204e9800998ecf8427e","time":{"start":1730657665696,"stop":1730657666254,"duration":558},"status":"broken","statusMessage":"Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n\nThe command that returned the promise was:\n\n  > `cy.wrap()`\n\nThe cy command you invoked inside the promise was:\n\n  > `cy.then()`\n\nBecause Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n\nCypress will resolve your command with whatever the final Cypress command yields.\n\nThe reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.\n\nhttps://on.cypress.io/returning-promise-and-commands-in-another-command","statusTrace":"CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n\nThe command that returned the promise was:\n\n  > `cy.wrap()`\n\nThe cy command you invoked inside the promise was:\n\n  > `cy.then()`\n\nBecause Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n\nCypress will resolve your command with whatever the final Cypress command yields.\n\nThe reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.\n\nhttps://on.cypress.io/returning-promise-and-commands-in-another-command\n    at <unknown> (https://api.clickup.com/__cypress/runner/cypress_runner.js:143880:62)\n    at tryCatcher (https://api.clickup.com/__cypress/runner/cypress_runner.js:1807:23)\n    at Promise._settlePromiseFromHandler (https://api.clickup.com/__cypress/runner/cypress_runner.js:1519:31)\n    at Promise._settlePromise (https://api.clickup.com/__cypress/runner/cypress_runner.js:1576:18)\n    at Promise._settlePromiseCtx (https://api.clickup.com/__cypress/runner/cypress_runner.js:1613:10)\n    at _drainQueueStep (https://api.clickup.com/__cypress/runner/cypress_runner.js:2411:12)\n    at _drainQueue (https://api.clickup.com/__cypress/runner/cypress_runner.js:2400:9)\n    at Async._drainQueues (https://api.clickup.com/__cypress/runner/cypress_runner.js:2416:5)\n    at Async.drainQueues (https://api.clickup.com/__cypress/runner/cypress_runner.js:2286:14)\nFrom Your Spec Code:\n    at Context.eval (webpack://vscode_cypress_ts_allure_circleci/./cypress/support/commands.ts:30:0)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n\nThe command that returned the promise was:\n\n  > `cy.wrap()`\n\nThe cy command you invoked inside the promise was:\n\n  > `cy.then()`\n\nBecause Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n\nCypress will resolve your command with whatever the final Cypress command yields.\n\nThe reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.\n\nhttps://on.cypress.io/returning-promise-and-commands-in-another-command","statusTrace":"CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n\nThe command that returned the promise was:\n\n  > `cy.wrap()`\n\nThe cy command you invoked inside the promise was:\n\n  > `cy.then()`\n\nBecause Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n\nCypress will resolve your command with whatever the final Cypress command yields.\n\nThe reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.\n\nhttps://on.cypress.io/returning-promise-and-commands-in-another-command\n    at <unknown> (https://api.clickup.com/__cypress/runner/cypress_runner.js:143880:62)\n    at tryCatcher (https://api.clickup.com/__cypress/runner/cypress_runner.js:1807:23)\n    at Promise._settlePromiseFromHandler (https://api.clickup.com/__cypress/runner/cypress_runner.js:1519:31)\n    at Promise._settlePromise (https://api.clickup.com/__cypress/runner/cypress_runner.js:1576:18)\n    at Promise._settlePromiseCtx (https://api.clickup.com/__cypress/runner/cypress_runner.js:1613:10)\n    at _drainQueueStep (https://api.clickup.com/__cypress/runner/cypress_runner.js:2411:12)\n    at _drainQueue (https://api.clickup.com/__cypress/runner/cypress_runner.js:2400:9)\n    at Async._drainQueues (https://api.clickup.com/__cypress/runner/cypress_runner.js:2416:5)\n    at Async.drainQueues (https://api.clickup.com/__cypress/runner/cypress_runner.js:2286:14)\nFrom Your Spec Code:\n    at Context.eval (webpack://vscode_cypress_ts_allure_circleci/./cypress/support/commands.ts:30:0)","steps":[{"name":"Get a list of Goals","time":{"start":1730657665719},"status":"unknown","steps":[{"name":"Command \"sentRequestT2\"","time":{"start":1730657666274,"stop":1730657665721,"duration":-553},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"Argument [0]","value":"GET"},{"name":"Argument [1]","value":"/team/9012430611/goal"},{"name":"Argument [2]","value":"null"}],"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":true,"stepsCount":0,"attachmentStep":false},{"name":"Trying to send GET request to /team/9012430611/goal","time":{"start":1730657665721,"stop":1730657666012,"duration":291},"status":"passed","steps":[{"name":"Command \"log\"","time":{"start":1730657666274,"stop":1730657665724,"duration":-550},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"Argument [0]","value":"Trying to send GET request to /team/9012430611/goal without body"}],"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":true,"stepsCount":0,"attachmentStep":false},{"name":"Command \"request\"","time":{"start":1730657666274,"stop":1730657666011,"duration":-263},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"Argument [0]","value":"{\"method\":\"GET\",\"url\":\"/team/9012430611/goal\",\"body\":null,\"failOnStatusCode\":false,\"headers\":{\"Authorization\":\"pk_152496286_63Q8..."}],"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":true,"stepsCount":0,"attachmentStep":false},{"name":"Command \"wrap\"","time":{"start":1730657666276,"stop":1730657666012,"duration":-264},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"Argument [0]","value":"{\"body\":{\"err\":\"Team not authorized\",\"ECODE\":\"OAUTH_060\"},\"headers\":{\"content-type\":\"application/json; charset=utf-8\",\"content-l..."}],"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":true,"stepsCount":0,"attachmentStep":false}],"attachments":[{"uid":"57e19ab441b43d8","name":"responseBody for GET /team/9012430611/goal","source":"57e19ab441b43d8.json","type":"application/json","size":49}],"parameters":[],"attachmentsCount":1,"shouldDisplayMessage":false,"hasContent":true,"stepsCount":3,"attachmentStep":false},{"name":"Command \"wrap\"","time":{"start":1730657666276,"stop":1730657666020,"duration":-256},"status":"broken","statusMessage":"Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n\nThe command that returned the promise was:\n\n  > `cy.wrap()`\n\nThe cy command you invoked inside the promise was:\n\n  > `cy.then()`\n\nBecause Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n\nCypress will resolve your command with whatever the final Cypress command yields.\n\nThe reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.\n\nhttps://on.cypress.io/returning-promise-and-commands-in-another-command","statusTrace":"CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n\nThe command that returned the promise was:\n\n  > `cy.wrap()`\n\nThe cy command you invoked inside the promise was:\n\n  > `cy.then()`\n\nBecause Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n\nCypress will resolve your command with whatever the final Cypress command yields.\n\nThe reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.\n\nhttps://on.cypress.io/returning-promise-and-commands-in-another-command\n    at <unknown> (https://api.clickup.com/__cypress/runner/cypress_runner.js:143880:62)\n    at tryCatcher (https://api.clickup.com/__cypress/runner/cypress_runner.js:1807:23)\n    at Promise._settlePromiseFromHandler (https://api.clickup.com/__cypress/runner/cypress_runner.js:1519:31)\n    at Promise._settlePromise (https://api.clickup.com/__cypress/runner/cypress_runner.js:1576:18)\n    at Promise._settlePromiseCtx (https://api.clickup.com/__cypress/runner/cypress_runner.js:1613:10)\n    at _drainQueueStep (https://api.clickup.com/__cypress/runner/cypress_runner.js:2411:12)\n    at _drainQueue (https://api.clickup.com/__cypress/runner/cypress_runner.js:2400:9)\n    at Async._drainQueues (https://api.clickup.com/__cypress/runner/cypress_runner.js:2416:5)\n    at Async.drainQueues (https://api.clickup.com/__cypress/runner/cypress_runner.js:2286:14)\nFrom Your Spec Code:\n    at Context.eval (webpack://vscode_cypress_ts_allure_circleci/./cypress/support/commands.ts:30:0)","steps":[],"attachments":[],"parameters":[{"name":"Argument [0]","value":"{\"specWindow\":{\"document\":{},\"name\":\"\",\"location\":{\"href\":\"https://api.clickup.com/__cypress/iframes/cypress%5Ce2e%5Capi-tests%5..."}],"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true,"stepsCount":0,"attachmentStep":false}],"attachments":[{"uid":"ce9dd04e6c59a5af","name":"Screenshot","source":"ce9dd04e6c59a5af.png","type":"image/png","size":50484}],"parameters":[],"attachmentsCount":2,"shouldDisplayMessage":false,"hasContent":true,"stepsCount":6,"attachmentStep":false}],"attachments":[],"parameters":[],"attachmentsCount":2,"shouldDisplayMessage":false,"hasContent":true,"stepsCount":7,"attachmentStep":false},"afterStages":[],"labels":[{"name":"language","value":"javascript"},{"name":"framework","value":"cypress"},{"name":"parentSuite","value":"Check goals functionality on clickup"},{"name":"host","value":"Keyushka"},{"name":"thread","value":"pid-55524-worker-main"},{"name":"package","value":"cypress.e2e.api-tests.goals.cy.ts"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"7050924f65451d3.json","parameterValues":[]}